### ISSUE TITLE
Did you ever have a Craft 2 version?

### ISSUE THREAD

**Issue by JayBox325** [a-digital/zendesk#1]
I just need to add a zendesk form to Craft but don't have the time to upgrade it to craft 3, just wondering if there was a Craft 2 project for this?

Thanks,
Jay

**Comment by matt-adigital** [comment]
Hi Jay,

We used this internally on Craft 2 for a period but this was then upgraded to Craft 3 before being released. We never released the Craft 2 version and there were a lot of changes made during the upgrade process.

As a result I don't have a working Craft 2 version any longer but it could be worth porting this plugin again to help people in your position where upgrading to Craft 3 might not be an option. I'll add it to our internal to-do list.

**Comment by JayBox325** [comment]
Hi Matt, thanks for getting back to me.

Since this we have done a bit of research and we have just modified the contact-form plugin from P&T so send the contact form contents to our Zendesk email address and Zendesk makes it a ticket without a plugin on their end.

Thanks,
Jay

**Comment by matt-adigital** [comment]
You're welcome, sorry it was a delayed response. I'm glad to hear that you found a solution to get the tickets created in Zendesk.

I'll still work on a Craft 2 version though as that will then enable submissions to populate any custom fields which may have been set up on the tickets. I'll update this issue when I've got it built and released.

**Comment by matt-adigital** [comment]
I've released a Craft 2 version now which is available on this repo as a separate branch.

https://github.com/a-digital/zendesk/tree/craft2
